### PR TITLE
Enumerable

### PR DESCRIPTION
**Pull request by yin-ka**
In this PR, I:
- Created a module MyEnumerable that implements the following methods with the same functionality as in the enumerable methods:
  - #all?
  - #any?
  - #filter
- Each class and module has a separate .rb file.

### CODE REVIEW

**Comment by KDlamini** [comment]
## Status: Invalid 🔴 

### Hi team @yin-ka, @DianaBeki 🙋‍♀️,  

While you made a great effort in this project, I can't review your code.

## Invalid Code Review Request
 
You have submitted a project that has a README that is not professional. Here is a key point to consider when documenting your README.

- All main headers from the [README template](https://github.com/microverseinc/readme-template) should be present. Kindly add the `Future Features` section and make sure to include 1-3 potential features to be added. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by yin-ka** [comment]
> unless

**Comment by yin-ka** [comment]
> ## Status: Invalid 🔴
> ### Hi team @yin-ka, @DianaBeki 🙋‍♀️,
> While you made a great effort in this project, I can't review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project that has a README that is not professional. Here is a key point to consider when documenting your README.
> 
> * All main headers from the [README template](https://github.com/microverseinc/readme-template) should be present. Kindly add the `Future Features` section and make sure to include 1-3 potential features to be added.
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @KDlamini in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

Thanks @KDlamini, I will make the necessary changes ASAP

**Review by LionRouge1 — APPROVED** [review]
Hi **Team**, 

# STATUS: APPROVED! 🥇 💯 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

done

## Highlights
- Great job, your project is error free :+1: 
- Nice work you meet all the requirements :1st_place_medal: 
- All linters passed :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
